import type { CharacterPalette, Direction, SpriteFrame, SpriteTemplate } from "../types";

type ActionTemplates = {
  walking: [SpriteTemplate, SpriteTemplate, SpriteTemplate];
  typing: [SpriteTemplate, SpriteTemplate];
  reading: [SpriteTemplate, SpriteTemplate];
  idle: [SpriteTemplate];
};

export type SpriteTemplatesByDirection = Record<"down" | "up" | "right", ActionTemplates>;

function toTemplate(rows: string[]): SpriteTemplate {
  return rows.map((row) => row.split(""));
}

function flipTemplate(template: SpriteTemplate): SpriteTemplate {
  return template.map((row) => [...row].reverse());
}

function replaceRows(base: SpriteTemplate, updates: Record<number, string>): SpriteTemplate {
  return base.map((row, index) => {
    const next = updates[index];
    return next ? next.split("") : [...row];
  });
}

const DOWN_WALK_1 = toTemplate([
  "________________",
  "_____HHHHHH_____",
  "____HHHHHHHH____",
  "____HHKKKKHH____",
  "___HHKKEEKKHH___",
  "___HKKKKKKKKH___",
  "____HHKKKKHH____",
  "_____SSSSSS_____",
  "____SSSSSSSS____",
  "___SSSKKKKSSS___",
  "___SSSSSSSSSS___",
  "___S__SSSS__S___",
  "______PPPP______",
  "_____PPPPPP_____",
  "_____PP__PP_____",
  "_____OO__OO_____",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
]);

const DOWN_WALK_2 = replaceRows(DOWN_WALK_1, {
  14: "_____P___PP_____",
  15: "_____O___OO_____",
});

const DOWN_WALK_3 = replaceRows(DOWN_WALK_1, {
  14: "_____PP___P_____",
  15: "_____OO___O_____",
});

const DOWN_TYPING_1 = replaceRows(DOWN_WALK_1, {
  10: "__SSSSSSSSSSSS__",
  11: "__SKKSSSSSSKKS__",
  12: "_____PPPPPP_____",
});

const DOWN_TYPING_2 = replaceRows(DOWN_TYPING_1, {
  10: "__SSSSSSSSSSS___",
  11: "___KKSSSSSSKK___",
});

const DOWN_READING_1 = replaceRows(DOWN_WALK_1, {
  8: "___SSS__SSSS____",
  9: "___SSSKKSSKSS___",
  10: "___SSSSSSSSSS___",
});

const DOWN_READING_2 = replaceRows(DOWN_READING_1, {
  7: "_____SSSSS______",
  8: "____SSS__SSS____",
  9: "___SSKKSSSKSS___",
});

const DOWN_IDLE = replaceRows(DOWN_WALK_1, {
  14: "_____PPPPPP_____",
  15: "_____OO__OO_____",
});

const UP_WALK_1 = toTemplate([
  "________________",
  "_____HHHHHH_____",
  "____HHHHHHHH____",
  "____HHKKKKHH____",
  "___HHKKKKKKHH___",
  "___HKKKKKKKKH___",
  "____HHKKKKHH____",
  "_____SSSSSS_____",
  "____SSSSSSSS____",
  "___SSSSSSSSSS___",
  "___SSSKKKKSSS___",
  "___S__SSSS__S___",
  "______PPPP______",
  "_____PPPPPP_____",
  "_____PP__PP_____",
  "_____OO__OO_____",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
]);

const UP_WALK_2 = replaceRows(UP_WALK_1, {
  14: "_____P___PP_____",
  15: "_____O___OO_____",
});

const UP_WALK_3 = replaceRows(UP_WALK_1, {
  14: "_____PP___P_____",
  15: "_____OO___O_____",
});

const UP_TYPING_1 = replaceRows(UP_WALK_1, {
  9: "__SSSSSSSSSSSS__",
  10: "__SKKSSSSSSKKS__",
});

const UP_TYPING_2 = replaceRows(UP_TYPING_1, {
  9: "__SSSSSSSSSSS___",
  10: "___KKSSSSSSKK___",
});

const UP_READING_1 = replaceRows(UP_WALK_1, {
  7: "___SSS__SSSS____",
  8: "___SSSKKSSKSS___",
});

const UP_READING_2 = replaceRows(UP_READING_1, {
  6: "_____SSSSS______",
  7: "____SSS__SSS____",
  8: "___SSKKSSSKSS___",
});

const UP_IDLE = replaceRows(UP_WALK_1, {
  14: "_____PPPPPP_____",
  15: "_____OO__OO_____",
});

const RIGHT_WALK_1 = toTemplate([
  "________________",
  "______HHHH______",
  "_____HHHHHH_____",
  "_____HKKKKH_____",
  "____HHKKEEKHH___",
  "____HKKKKKKKH___",
  "_____HKKKKHH____",
  "_____SSSSSS_____",
  "____SSSSSSSS____",
  "___SSSSKKKSSS___",
  "___SSSSSSSSSS___",
  "___SS__SS__SS___",
  "______PPPP______",
  "_____PPPPPP_____",
  "_____PP__PP_____",
  "_____OO__OO_____",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
  "________________",
]);

const RIGHT_WALK_2 = replaceRows(RIGHT_WALK_1, {
  14: "_____P___PP_____",
  15: "_____O___OO_____",
});

const RIGHT_WALK_3 = replaceRows(RIGHT_WALK_1, {
  14: "_____PP___P_____",
  15: "_____OO___O_____",
});

const RIGHT_TYPING_1 = replaceRows(RIGHT_WALK_1, {
  9: "____SSSSSSSSSS__",
  10: "____SSSSSSSKKS__",
  11: "_____SSSSSSKK___",
});

const RIGHT_TYPING_2 = replaceRows(RIGHT_TYPING_1, {
  10: "_____SSSSSSKKS__",
  11: "____SSSSSSSKK___",
});

const RIGHT_READING_1 = replaceRows(RIGHT_WALK_1, {
  7: "____SSSSS_______",
  8: "___SSSSSKKSS____",
  9: "___SSSSSSSSS____",
});

const RIGHT_READING_2 = replaceRows(RIGHT_READING_1, {
  6: "_____SSS________",
  7: "____SSSSS_______",
  8: "___SSSSKKSSS____",
});

const RIGHT_IDLE = replaceRows(RIGHT_WALK_1, {
  14: "_____PPPPPP_____",
  15: "_____OO__OO_____",
});

export const SPRITE_TEMPLATES: SpriteTemplatesByDirection = {
  down: {
    walking: [DOWN_WALK_1, DOWN_WALK_2, DOWN_WALK_3],
    typing: [DOWN_TYPING_1, DOWN_TYPING_2],
    reading: [DOWN_READING_1, DOWN_READING_2],
    idle: [DOWN_IDLE],
  },
  up: {
    walking: [UP_WALK_1, UP_WALK_2, UP_WALK_3],
    typing: [UP_TYPING_1, UP_TYPING_2],
    reading: [UP_READING_1, UP_READING_2],
    idle: [UP_IDLE],
  },
  right: {
    walking: [RIGHT_WALK_1, RIGHT_WALK_2, RIGHT_WALK_3],
    typing: [RIGHT_TYPING_1, RIGHT_TYPING_2],
    reading: [RIGHT_READING_1, RIGHT_READING_2],
    idle: [RIGHT_IDLE],
  },
};

export function resolveTemplate(template: SpriteTemplate, palette: CharacterPalette): SpriteFrame {
  const colorMap: Record<string, string | null> = {
    _: null,
    H: palette.hair,
    K: palette.skin,
    S: palette.shirt,
    P: palette.pants,
    O: palette.shoes,
    E: palette.eyes,
  };

  return template.map((row) =>
    row.map((pixel) => {
      if (pixel in colorMap) {
        return colorMap[pixel] ?? null;
      }
      return null;
    }),
  );
}

const TRANSPARENT = null;

function colorRow(...pixels: (string | null)[]): (string | null)[] {
  return pixels;
}

export const FURNITURE_SPRITES: Record<string, SpriteFrame> = {
  desk: [
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#6b7280", "#6b7280", "#6b7280", "#6b7280", "#6b7280", "#6b7280", "#6b7280", "#6b7280", "#6b7280", "#6b7280", "#6b7280", "#6b7280", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#8b8b95", "#8b8b95", "#8b8b95", "#8b8b95", "#8b8b95", "#8b8b95", "#8b8b95", "#8b8b95", "#8b8b95", "#8b8b95", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#27272a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#27272a", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
  ],
  chair: [
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#71717a", "#71717a", "#71717a", "#71717a", "#71717a", "#71717a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#71717a", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#71717a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT, "#3f3f46", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
  ],
  plant: [
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#22c55e", "#22c55e", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#22c55e", "#4ade80", "#4ade80", "#22c55e", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#22c55e", "#4ade80", "#4ade80", "#4ade80", "#4ade80", "#22c55e", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#16a34a", "#22c55e", "#4ade80", "#22c55e", "#22c55e", "#4ade80", "#22c55e", "#16a34a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#16a34a", "#22c55e", "#4ade80", "#4ade80", "#22c55e", "#16a34a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#16a34a", "#22c55e", "#22c55e", "#16a34a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#78350f", "#78350f", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#78350f", "#92400e", "#a16207", "#a16207", "#92400e", "#78350f", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#78350f", "#78350f", "#78350f", "#78350f", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
  ],
  monitor: [
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, "#111827", "#0f172a", "#1e3a5f", "#0f172a", "#1e3a5f", "#0f172a", "#1e3a5f", "#0f172a", "#1e3a5f", "#111827", TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, "#111827", "#1e3a5f", "#22d3ee", "#1e3a5f", "#1e3a5f", "#22d3ee", "#1e3a5f", "#1e3a5f", "#0f172a", "#111827", TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, "#111827", "#0f172a", "#1e3a5f", "#22d3ee", "#1e3a5f", "#1e3a5f", "#1e3a5f", "#22d3ee", "#1e3a5f", "#111827", TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, "#111827", "#1e3a5f", "#1e3a5f", "#1e3a5f", "#22d3ee", "#1e3a5f", "#22d3ee", "#1e3a5f", "#0f172a", "#111827", TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", "#111827", TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#3f3f46", "#3f3f46", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#3f3f46", "#3f3f46", "#3f3f46", "#3f3f46", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
  ],
  bookshelf: [
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#78350f", "#b91c1c", "#1e40af", "#78350f", "#b91c1c", "#1e40af", "#78350f", "#b91c1c", "#1e40af", "#78350f", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#92400e", "#dc2626", "#2563eb", "#92400e", "#dc2626", "#2563eb", "#92400e", "#dc2626", "#2563eb", "#92400e", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#92400e", "#dc2626", "#2563eb", "#92400e", "#dc2626", "#2563eb", "#92400e", "#dc2626", "#2563eb", "#92400e", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#166534", "#a16207", "#166534", "#a16207", "#166534", "#a16207", "#166534", "#a16207", "#166534", "#a16207", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#22c55e", "#d97706", "#22c55e", "#d97706", "#22c55e", "#d97706", "#22c55e", "#d97706", "#22c55e", "#d97706", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#22c55e", "#d97706", "#22c55e", "#d97706", "#22c55e", "#d97706", "#22c55e", "#d97706", "#22c55e", "#d97706", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#7c3aed", "#7c3aed", "#0891b2", "#0891b2", "#7c3aed", "#0891b2", "#7c3aed", "#0891b2", "#7c3aed", "#0891b2", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#8b5cf6", "#8b5cf6", "#22d3ee", "#22d3ee", "#8b5cf6", "#22d3ee", "#8b5cf6", "#22d3ee", "#8b5cf6", "#22d3ee", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", "#52525b", TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
  ],
  water_cooler: [
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#bfdbfe", "#bfdbfe", "#bfdbfe", "#bfdbfe", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#93c5fd", "#bfdbfe", "#e0f2fe", "#e0f2fe", "#bfdbfe", "#93c5fd", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#93c5fd", "#bfdbfe", "#e0f2fe", "#e0f2fe", "#bfdbfe", "#93c5fd", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#93c5fd", "#93c5fd", "#bfdbfe", "#bfdbfe", "#93c5fd", "#93c5fd", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#71717a", "#71717a", "#71717a", "#71717a", "#71717a", "#71717a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#71717a", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#71717a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#71717a", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#a1a1aa", "#71717a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#71717a", "#71717a", "#71717a", "#71717a", "#71717a", "#71717a", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#52525b", TRANSPARENT, TRANSPARENT, "#52525b", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#52525b", TRANSPARENT, TRANSPARENT, "#52525b", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, "#3f3f46", "#3f3f46", "#3f3f46", "#3f3f46", "#3f3f46", "#3f3f46", TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
    colorRow(TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT),
  ],
};

export const CHARACTER_SPRITES = {
  idle: {
    down: SPRITE_TEMPLATES.down.idle.map((template) => template),
    up: SPRITE_TEMPLATES.up.idle.map((template) => template),
    right: SPRITE_TEMPLATES.right.idle.map((template) => template),
    left: SPRITE_TEMPLATES.right.idle.map((template) => flipTemplate(template)),
  },
  walking: {
    down: SPRITE_TEMPLATES.down.walking.map((template) => template),
    up: SPRITE_TEMPLATES.up.walking.map((template) => template),
    right: SPRITE_TEMPLATES.right.walking.map((template) => template),
    left: SPRITE_TEMPLATES.right.walking.map((template) => flipTemplate(template)),
  },
  typing: {
    down: SPRITE_TEMPLATES.down.typing.map((template) => template),
    up: SPRITE_TEMPLATES.up.typing.map((template) => template),
    right: SPRITE_TEMPLATES.right.typing.map((template) => template),
    left: SPRITE_TEMPLATES.right.typing.map((template) => flipTemplate(template)),
  },
  reading: {
    down: SPRITE_TEMPLATES.down.reading.map((template) => template),
    up: SPRITE_TEMPLATES.up.reading.map((template) => template),
    right: SPRITE_TEMPLATES.right.reading.map((template) => template),
    left: SPRITE_TEMPLATES.right.reading.map((template) => flipTemplate(template)),
  },
  offline: {
    down: SPRITE_TEMPLATES.down.idle.map((template) => template),
    up: SPRITE_TEMPLATES.up.idle.map((template) => template),
    right: SPRITE_TEMPLATES.right.idle.map((template) => template),
    left: SPRITE_TEMPLATES.right.idle.map((template) => flipTemplate(template)),
  },
} as const satisfies Record<string, Record<Direction, SpriteTemplate[]>>;
